const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //admin

  FETCH_ALLUSER_SUCCESS: "FETCH_ALLUSER_SUCCESS",
  FETCH_ALLUSER_FAILED: "FETCH_ALLUSER_FAILED",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILED: "EDIT_USER_FAILED",

  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",

  DELETE_USER_SUCCESS: "CREATE_DELETE_SUCCESS",
  DELETE_USER_FAILED: "CREATE_DELETE_FAILED",

  FETCH_ALLTOPIC_SUCCESS: "FETCH_ALLTOPIC_SUCCESS",
  FETCH_ALLTOPIC_FAILED: "FETCH_ALLTOPIC_FAILED",

  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
});

export default actionTypes;
